# Generated by Django 5.0 on 2023-12-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_alter_user_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
