# Generated by Django 5.0 on 2023-12-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0005_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
